spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
# mysql 연결 시 사용
#    url: jdbc:mysql://database-1.cymwmpm0yhqt.ap-northeast-2.rds.amazonaws.com/bbangbbang?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect // MySQL 연결 시 사용
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
mail:
  address:
    admin: test@test.com

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 360

logging:
  level:
    org:
      springframework:
        security: DEBUG

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: "ap-northeast-2"
    stack:
      auto: false
